# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default 

steps:
- script: |
    # Install dependencies
    npm install --only=prod

    # Build React app
    npm run build
  displayName: 'Install dependencies and build'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: |
       src/*
       public/*
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy project files'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'
  displayName: 'Publish npm artifact'
# - task: PublishBuildArtifacts@1
#   inputs:
#     pathtoPublish: '$(Build.SourcesDirectory)'
#     artifactName: 'drop'
#     publishLocation: 'Container'
#   displayName: 'Publish Artifact'
