# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default 
  
variables:
  buildArtifactStagingDirectory: '/dist'

steps:
- script: |
    # Install dependencies
    npm install

    # Build React app
    npm run build
  displayName: 'Install dependencies and build'

- task: CopyFiles@2
  inputs:
    sourceFolder: 'dist'
    targetFolder: '$(buildArtifactStagingDirectory)'
  displayName: 'Copy Built Files to Staging Directory'

