# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dockerized-frontend

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker'
        repository: 'ayaandanish/chatbot-frontend'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'dist'
        ArtifactName: 'dockerized-frontend-artifact'
        publishLocation: 'Container'
      displayName: 'Publish Artifact'
    